name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
   deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./repo
          file: ./repo/Dockerfile
          push: false
          load: true
          tags: ghcr.io/unikraft/docs:base
          cache-from: type=gha
          cache-to: type=gha

      - name: Load image
        run: |
          docker image list
          docker run -v $GITHUB_WORKSPACE/repo:/docs -w /docs --entrypoint sh ghcr.io/unikraft/docs:base scripts/deploy.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
